# SPDX-License-Identifier: GPL-2.0

# ZHIHE Platform Support
snd-soc-zhihe-objs		:= zhihe-pcm-dma.o zhihe-dummy-pcm.o
snd-soc-zhihe-i2s-objs		:= zhihe-i2s.o
snd-soc-zhihe-tdm-objs		:= zhihe-tdm.o
snd-soc-zhihe-pdm-objs		:= zhihe-pdm.o

obj-$(CONFIG_SND_SOC_ZHIHE)		+= snd-soc-zhihe.o
obj-$(CONFIG_SND_SOC_ZHIHE_I2S)		+= snd-soc-zhihe-i2s.o
obj-$(CONFIG_SND_SOC_ZHIHE_TDM)		+= snd-soc-zhihe-tdm.o
obj-$(CONFIG_SND_SOC_ZHIHE_PDM)		+= snd-soc-zhihe-pdm.o
